### ISSUE TITLE
Concept of Ground-Segmentation

### ISSUE THREAD

**Issue by SwatiMatta** [Kartik17/Ground-Segmentation-Lidar#3]
Hi Karthik,

Can you please share the reference paper or any link that explains the concept of Ground Segmentation that you have implemented.

Thanks.

**Comment by Kartik17** [comment]
1. Sample a set of lowest points in the vertical direction.
2. Compute the Covariance matrix using these points
3. Do SVD and find the eigenvector corresponding to the smallest Singular Value, as this would correspond to the direction of the least variance.
4. Update the plane equation, and find more points that are close to the plane, and repeat till normal converges.

**Comment by sondonghyo** [comment]
Thank you! This work helps me either.
